/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : string,
  'content' : string,
  'sender' : string,
  'timestamp' : Time,
  'roomId' : string,
}
export interface Report {
  'id' : string,
  'reportedUser' : [] | [string],
  'room' : string,
  'timestamp' : Time,
  'reportedMessage' : [] | [string],
  'reporter' : string,
  'reason' : string,
}
export interface Room {
  'id' : string,
  'creator' : Principal,
  'name' : string,
  'createdTimestamp' : Time,
  'location' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'joinedTimestamp' : Time,
  'lastUpdated' : Time,
  'avatarURL' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_getInternalState' : ActorMethod<
    [],
    {
      'messageCounter' : bigint,
      'mutes' : Array<[Principal, Array<string>]>,
      'messages' : Array<[string, Array<Message>]>,
      'roomCounter' : bigint,
      'reportCounter' : bigint,
      'blocks' : Array<[Principal, Array<string>]>,
      'reports' : Array<[string, Array<Report>]>,
      'profiles' : Array<[Principal, UserProfile]>,
      'rooms' : Array<[string, Room]>,
    }
  >,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[string], undefined>,
  'createRoom' : ActorMethod<[string, [] | [string]], Room>,
  'deleteCallerUserProfile' : ActorMethod<[], undefined>,
  'getBlocks' : ActorMethod<[Principal], [] | [Array<string>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[string, [] | [Time]], Array<Message>>,
  'getMessagesForRoom' : ActorMethod<[string], [] | [Array<Message>]>,
  'getMutes' : ActorMethod<[Principal], [] | [Array<string>]>,
  'getReportsForRoom' : ActorMethod<[string], [] | [Array<Report>]>,
  'getRoom' : ActorMethod<[string], [] | [Room]>,
  'getRoomsByLocation' : ActorMethod<[[] | [string]], Array<Room>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'muteUser' : ActorMethod<[string], undefined>,
  'reportContent' : ActorMethod<
    [[] | [string], [] | [string], string, string],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string, string], Message>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];