/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'senderPrincipal' : IDL.Opt(IDL.Principal),
  'timestamp' : Time,
  'roomId' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Text,
  'reportedUser' : IDL.Opt(IDL.Text),
  'room' : IDL.Text,
  'timestamp' : Time,
  'reportedMessage' : IDL.Opt(IDL.Text),
  'reporter' : IDL.Text,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'joinedTimestamp' : Time,
  'lastUpdated' : Time,
  'avatarURL' : IDL.Text,
});
export const Room = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'name' : IDL.Text,
  'createdTimestamp' : Time,
  'location' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_getInternalState' : IDL.Func(
      [],
      [
        IDL.Record({
          'bannedUsers' : IDL.Vec(IDL.Principal),
          'messageCounter' : IDL.Nat,
          'mutes' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text))),
          'messages' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Message))),
          'roomCounter' : IDL.Nat,
          'reportCounter' : IDL.Nat,
          'blocks' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text))),
          'reports' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Report))),
          'profiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
          'rooms' : IDL.Vec(IDL.Tuple(IDL.Text, Room)),
        }),
      ],
      ['query'],
    ),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'blockUser' : IDL.Func([IDL.Text], [], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Room], []),
  'deleteCallerUserProfile' : IDL.Func([], [], []),
  'deleteMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteRoom' : IDL.Func([IDL.Text], [], []),
  'getBlocks' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessagesForRoom' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(Message))],
      ['query'],
    ),
  'getMutes' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'getReportsForRoom' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(Report))],
      ['query'],
    ),
  'getRoom' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
  'getRoomsByLocation' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Room)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'muteUser' : IDL.Func([IDL.Text], [], []),
  'reportContent' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Message], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'senderPrincipal' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'roomId' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Text,
    'reportedUser' : IDL.Opt(IDL.Text),
    'room' : IDL.Text,
    'timestamp' : Time,
    'reportedMessage' : IDL.Opt(IDL.Text),
    'reporter' : IDL.Text,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'joinedTimestamp' : Time,
    'lastUpdated' : Time,
    'avatarURL' : IDL.Text,
  });
  const Room = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'name' : IDL.Text,
    'createdTimestamp' : Time,
    'location' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_getInternalState' : IDL.Func(
        [],
        [
          IDL.Record({
            'bannedUsers' : IDL.Vec(IDL.Principal),
            'messageCounter' : IDL.Nat,
            'mutes' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text))),
            'messages' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Message))),
            'roomCounter' : IDL.Nat,
            'reportCounter' : IDL.Nat,
            'blocks' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Text))),
            'reports' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(Report))),
            'profiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
            'rooms' : IDL.Vec(IDL.Tuple(IDL.Text, Room)),
          }),
        ],
        ['query'],
      ),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'blockUser' : IDL.Func([IDL.Text], [], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Room], []),
    'deleteCallerUserProfile' : IDL.Func([], [], []),
    'deleteMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteRoom' : IDL.Func([IDL.Text], [], []),
    'getBlocks' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessagesForRoom' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Message))],
        ['query'],
      ),
    'getMutes' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'getReportsForRoom' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Report))],
        ['query'],
      ),
    'getRoom' : IDL.Func([IDL.Text], [IDL.Opt(Room)], ['query']),
    'getRoomsByLocation' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Room)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'muteUser' : IDL.Func([IDL.Text], [], []),
    'reportContent' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Message], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };