/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : string,
  'content' : string,
  'sender' : string,
  'senderPrincipal' : [] | [Principal],
  'timestamp' : Time,
  'roomId' : string,
}
export interface Room {
  'id' : string,
  'creator' : Principal,
  'name' : string,
  'createdTimestamp' : Time,
  'location' : [] | [string],
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'joinedTimestamp' : Time,
  'lastUpdated' : Time,
  'avatarURL' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], boolean>,
  'blockUser' : ActorMethod<[string], undefined>,
  'createRoom' : ActorMethod<[string, [] | [string], string], Room>,
  'deleteAllMessagesInRoom' : ActorMethod<[string], boolean>,
  'deleteCallerUserProfile' : ActorMethod<[], undefined>,
  'deleteMessage' : ActorMethod<[string, string], boolean>,
  'deleteRoomWithPassword' : ActorMethod<[string, string], boolean>,
  'getBlocks' : ActorMethod<[Principal], [] | [Array<string>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesForRoom' : ActorMethod<[string], [] | [Array<Message>]>,
  'getMutes' : ActorMethod<[Principal], [] | [Array<string>]>,
  'getRoom' : ActorMethod<[string], [] | [Room]>,
  'getRoomsByLocation' : ActorMethod<[[] | [string]], Array<Room>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserBanned' : ActorMethod<[Principal], boolean>,
  'muteUser' : ActorMethod<[string], undefined>,
  'reportContent' : ActorMethod<
    [[] | [string], [] | [string], string, string],
    boolean
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string, string], Message>,
  'unbanUser' : ActorMethod<[Principal], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];